<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FixedIT.NotificationService-ce14a442-f86a-45ad-af03-0e605e1fc26f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.*" />
    <PackageReference Include="RabbitMQ.Client" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FixedIT.Shared\FixedIT.Shared.csproj" />
  </ItemGroup>
</Project>
